### ISSUE TITLE
Initial implementation for an unsigned bigint type

### ISSUE THREAD

**Issue by declty87** [declty87/numeric-rs#1]
# To-Do

- [x] Implement add operation
- [x] Implement sub operation
- [x] Implement mul operation
- [ ] Implement div operation
- [ ] Add tests
